name       : gnome-pie
version    : 0.6.8
release    : 1
source     :
    - https://github.com/Simmesimme/Gnome-Pie/archive/v0.6.8.tar.gz : af0e9758bb9f211df2984cf56c938eef8ed4e709e6f727c380b1ed9305fac011
license    : GPL-3.0
component  : desktop.gnome
summary    : Gnome-Pie is a circular application launcher for Linux.
description: |
    Gnome-Pie is a circular application launcher for Linux.
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pango)
    - pkgconfig(xtst)
    - vala
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
