name       : gnome-pie
version    : 0.6.9
release    : 2
source     :
    - https://github.com/Simmesimme/Gnome-Pie/archive/v0.6.9.tar.gz : 07de5d01198d473c3988ddf4bb38ac4e8d58cc82d46866ab0bb9c6710cdf123a
license    : GPL-3.0
component  : desktop.gnome
summary    : Gnome-Pie is a circular application launcher for Linux.
description: |
    Gnome-Pie is a circular application launcher for Linux.
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pango)
    - pkgconfig(xtst)
    - vala
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
