name       : gnome-pie
version    : 0.7.1
release    : 6
source     :
    - https://github.com/Simmesimme/Gnome-Pie/archive/v0.7.1.tar.gz : 930843d6fdc0d773581966847c626f4177060b6491ac34a4d006d5728fe66aea
license    : GPL-3.0
component  : desktop.gnome
summary    : Gnome-Pie is a circular application launcher for Linux.
description: |
    Gnome-Pie is a circular application launcher for Linux.
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(pango)
    - pkgconfig(xtst)
    - libarchive-devel
    - vala
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    rm -Rf $installdir/usr/share/locale/bg
    rm -Rf $installdir/usr/share/locale/de
    rm -Rf $installdir/usr/share/locale/es
    rm -Rf $installdir/usr/share/locale/fr
    rm -Rf $installdir/usr/share/locale/it
    rm -Rf $installdir/usr/share/locale/ko
    rm -Rf $installdir/usr/share/locale/lt
    rm -Rf $installdir/usr/share/locale/pl
    rm -Rf $installdir/usr/share/locale/pt_BR
    rm -Rf $installdir/usr/share/locale/ru
    rm -Rf $installdir/usr/share/locale/zh_CN
